services:
  # === PostgreSQL Database ===
  postgres:
    image: postgres:15
    container_name: kmes-postgres
    environment:
      POSTGRES_DB: historydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka
    container_name: kafka
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9092:9092"
    restart: unless-stopped

  # === Historian Service ===
  historian:
    build: 
      context: ./historian
      dockerfile: Dockerfile
    container_name: kmes-historian
    env_file:
      - ./historian/.env
    ports:
      - "5002:5002"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: unless-stopped

  # === Emulator ===
  emulator:
    build:
      context: ./emulators/modbus
      dockerfile: Dockerfile
    container_name: modbus-emulator
    restart: unless-stopped

  # === RTDS (Real-Time Data Service) ===
  rtds:
    build:
      context: ./rtds
      dockerfile: Dockerfile
    container_name: kmes-rtds
    env_file:
      - ./rtds/.env
    ports:
      - "5002:5002"
    depends_on:
      - kafka
      - postgres
      - emulator
    restart: unless-stopped

  # === Prometheus ===
  prometheus:
    image: prom/prometheus:latest
    container_name: kmes-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/consoles'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped

  # === Grafana (опционально) ===
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: kmes-grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     GF_SECURITY_ADMIN_PASSWORD: admin
  #     GF_USERS_ALLOW_SIGN_UP: false
  #   volumes:
  #     - grafana_storage:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   depends_on:
  #     - prometheus
  #   restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:
  # grafana_storage: