{
 "title": "HISTORIAN Demo",
 "description": "Демонстрация данных RTDS сервером",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RTDS. Косинус",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "historydb",
     "rawSql": "SELECT\r\n  time_bucket('5 second', tag_time) AS time,\r\n  AVG(value) AS value\r\nFROM history_floats\r\nWHERE $__timeFilter(tag_time) and tag_id='Tag_6'\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "RTDS. Синусоида",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "historydb",
     "rawSql": "SELECT\r\n  time_bucket('5 second', tag_time) AS time,\r\n  AVG(value) AS value\r\nFROM history_floats\r\nWHERE $__timeFilter(tag_time) and tag_id='Tag_5'\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "RTDS. Пила",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "historydb",
     "rawSql": "SELECT\r\n  time_bucket('1 second', tag_time) AS time,\r\n  AVG(value) AS value\r\nFROM history_floats\r\nWHERE $__timeFilter(tag_time) and tag_id='Tag_7'\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "RTDS. Трапеция",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "dataset": "historydb",
     "rawSql": "SELECT\r\n  time_bucket('1 second', tag_time) AS time,\r\n  AVG(value) AS value\r\nFROM history_floats\r\nWHERE $__timeFilter(tag_time) and tag_id='Tag_8'\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "RTDS. Линия",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "historydb",
     "rawSql": "SELECT\r\n  time_bucket('15 second', tag_time) AS time,\r\n  AVG(value) AS value\r\nFROM history_floats\r\nWHERE $__timeFilter(tag_time) and tag_id='Tag_9'\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "RTDS. Случайное значение",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "historydb",
     "rawSql": "SELECT\r\n  time_bucket('15 second', tag_time) AS time,\r\n  AVG(value) AS value\r\nFROM history_floats\r\nWHERE $__timeFilter(tag_time) and tag_id='Tag_10'\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  }
 ]
}