{
 "title": "RTDS. Мониторинг",
 "description": "Мониторинг работы RTDS сервера",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Статистика",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "connector_counter_total", "legendFormat": "__auto" },
    { "expr": "tag_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "process_memory_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RTDS. Скан цикл",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(scan_cycle_latency_sec_sum[1m])/rate(scan_cycle_latency_sec_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Коннектор. Цикл.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(connector_duration_sec_sum[1m])/rate(connector_duration_sec_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скрипт. Длительность выполнения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(script_duration_sec_sum[1m])/rate(script_duration_sec_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Производительность. Локальный буфер.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(store_duration_sec_sum[1m])/rate(store_duration_sec_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер локального буфера",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "store_rows_gauge_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Размер локального буфера",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "store_size_gauge_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Продусер. Производительность",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_duration_sec_sum[1m])/rate(kafka_producer_duration_sec_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}